### ISSUE TITLE
[Documentation] latest docker-compose documentation is missing a healthcheck for mariadb

### ISSUE THREAD

**Issue by kastl-ars** [eduMFA/eduMFA#473]
The `latest` documentation on docker compose is missing a health check for the MariaDB, which leads to a race condition. If the eduMFA container starts faster than the mariadb one (because e.g. the image for edumfa was pulled already), the database is unreachable.

The solution is to add a healthcheck to the mariadb container and have the edumfa container wait for a healthy state of mariadb.

https://mariadb.com/kb/en/using-healthcheck-sh/

I can create a PR this afternoon.

```
services:
   mariadb:
[...]
         - MARIADB_ROOT_PASSWORD=pass
      healthcheck:
        test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
        start_period: 10s
        interval: 10s
        timeout: 5s
        retries: 3
   edumfa:
[...]
         - EDUMFA_ADMIN_PASS=Passwort123
      depends_on:
        mariadb:
          condition: service_healthy
[...]
```
